id: PDDB540A5
initial_creation_type: input
source_metadata:
  title: Third Karmapa Series
  language: en
  description: 'Texts by and about the Third Karmapa, Rangjung Dorje (karma pa rang
    byung rdo rje, 1284–1339):'
  volume:
    3f138f340ef344beb06d528199ab39a4:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Aspiration Prayers
created_at: '2022-03-01T01:47:35.689858'
last_modified_at: '2022-03-01T01:47:35.689864'
